### ISSUE TITLE
 Segmentation fault on startup (linux) v0.4.0-alpha

### ISSUE THREAD

**Issue by klauspost** [ebitengine/purego#108]
Running the output from a compile crashes on startup:

```
$ ./s2c
Segmentation fault (core dumped)
```

```
$ gdb ./s2c
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
[...]

(gdb) r
Starting program: /home/user1/cmd/s2c/s2c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e2a540 in _int_malloc (av=av@entry=0x7ffff7f9fc80 <main_arena>, bytes=bytes@entry=640) at ./malloc/malloc.c:4375
4375    ./malloc/malloc.c: No such file or directory.
(gdb) where
#0  0x00007ffff7e2a540 in _int_malloc (av=av@entry=0x7ffff7f9fc80 <main_arena>, bytes=bytes@entry=640)
    at ./malloc/malloc.c:4375
#1  0x00007ffff7e2aa49 in tcache_init () at ./malloc/malloc.c:3245
#2  0x00007ffff7e2b25e in tcache_init () at ./malloc/malloc.c:3241
#3  __GI___libc_malloc (bytes=64) at ./malloc/malloc.c:3306
#4  0x0000000000657942 in github.com/ebitengine/purego/internal/fakecgo.call5 ()
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.4.0-alpha/internal/fakecgo/trampolines_linux_amd64.s:72
#5  0x000000000065744c in github.com/ebitengine/purego/internal/fakecgo.malloc (size=<optimized out>)
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.4.0-alpha/internal/fakecgo/symbols.go:25
#6  github.com/ebitengine/purego/internal/fakecgo.x_cgo_init (g=0x7ffff7f9fce0 <main_arena+96>, setg=6650208)
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.4.0-alpha/internal/fakecgo/go_linux_amd64.go:81
#7  0x0000000000657b8a in github.com/ebitengine/purego/internal/fakecgo.x_cgo_init (g=0x8e7340 <runtime.g0>,
    setg=4612384) at <autogenerated>:1
#8  0x00000000006577bc in x_cgo_init_trampoline ()
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.4.0-alpha/internal/fakecgo/trampolines_linux_amd64.s:29
#9  0x0000000000466d11 in runtime.rt0_go () at c:/go/src/runtime/asm_amd64.s:220
#10 0x0000000000000000 in ?? ()
```

Version 0.3.0 crashes as well:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e2a540 in _int_malloc (av=av@entry=0x7ffff7f9fc80 <main_arena>, bytes=bytes@entry=640) at ./malloc/malloc.c:4375
4375    ./malloc/malloc.c: No such file or directory.
(gdb) where
#0  0x00007ffff7e2a540 in _int_malloc (av=av@entry=0x7ffff7f9fc80 <main_arena>, bytes=bytes@entry=640)
    at ./malloc/malloc.c:4375
#1  0x00007ffff7e2aa49 in tcache_init () at ./malloc/malloc.c:3245
#2  0x00007ffff7e2b25e in tcache_init () at ./malloc/malloc.c:3241
#3  __GI___libc_malloc (bytes=64) at ./malloc/malloc.c:3306
#4  0x000000000065dee2 in github.com/ebitengine/purego/internal/fakecgo.call5 ()
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.3.0/internal/fakecgo/trampolines_linux_amd64.s:72
#5  0x000000000065d9ec in github.com/ebitengine/purego/internal/fakecgo.malloc (size=<optimized out>)
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.3.0/internal/fakecgo/symbols.go:25
#6  github.com/ebitengine/purego/internal/fakecgo.x_cgo_init (g=0x7ffff7f9fce0 <main_arena+96>, setg=6676224)
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.3.0/internal/fakecgo/go_linux_amd64.go:81
#7  0x000000000065e12a in github.com/ebitengine/purego/internal/fakecgo.x_cgo_init (g=0x8f5dc0 <runtime.g0>,
    setg=4615808) at <autogenerated>:1
#8  0x000000000065dd5c in x_cgo_init_trampoline ()
    at e:/gopath/pkg/mod/github.com/ebitengine/purego@v0.3.0/internal/fakecgo/trampolines_linux_amd64.s:29
#9  0x0000000000467a71 in runtime.rt0_go () at c:/go/src/runtime/asm_amd64.s:220
#10 0x0000000000000000 in ?? ()
```

Go versions tested (for compile):

```
λ go version
go version go1.19.5 windows/amd64
λ SET GOOS=linux
λ go build .

or 

λ go version
go version go1.20.1 windows/amd64
λ SET GOOS=linux
λ go build .
```

All crash on startup.

**Comment by klauspost** [comment]
Similar issues: #101 #106

**Comment by klauspost** [comment]
Just saw the assembly. It is also a MOVAPS. Duplicate of  #106
