### ISSUE TITLE
test failed with Go 1.15 and Go 1.16

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#25]
I think this is the same issue as https://github.com/hajimehoshi/oto/issues/183

```
$ go1.15.15 test ./...
?       github.com/ebitengine/purego    [no test files]
?       github.com/ebitengine/purego/internal/fakecgo   [no test files]
?       github.com/ebitengine/purego/internal/strings   [no test files]
--- FAIL: ExampleAllocateClassPair (0.00s)
panic: runtime error: index out of range [18056875977166063944] with length 2000 [recovered]
        panic: runtime error: index out of range [18056875977166063944] with length 2000

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc00009dd28, 0x0, 0x0, 0xd67a, 0x113f920, 0xc000018420, 0x10144d4)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/example.go:89 +0x648
testing.runExample.func2(0xc0b9b04c927ab680, 0x861ae, 0x1237440, 0xc000010050, 0xc000010018, 0xc000072240, 0xc000051d28, 0xc00009dd58)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/run_example.go:58 +0x10d
panic(0x113f920, 0xc000018420)
        /Users/hajimehoshi/sdk/go1.15.15/src/runtime/panic.go:969 +0x1b9
github.com/ebitengine/purego.callbackWrap(0x110fb60)
        /Users/hajimehoshi/purego/syscall_darwin.go:102 +0x50f
github.com/ebitengine/purego.syscall_syscall9X(0x7ff80afe3400, 0x600000004090, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/hajimehoshi/purego/syscall_darwin.go:20 +0x128
github.com/ebitengine/purego.SyscallN(0x7ff80afe3400, 0xc00001a1e0, 0x2, 0x2, 0x0, 0xc00001a1e0, 0x2)
        /Users/hajimehoshi/purego/syscall.go:37 +0x11e
github.com/ebitengine/purego/objc.ID.Send(0x600000004090, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin.go:52 +0xb7
github.com/ebitengine/purego/objc_test.ExampleAllocateClassPair()
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin_test.go:22 +0x1b3
testing.runExample(0x1152cb4, 0x18, 0x1158988, 0x11503b1, 0xd, 0x0, 0x0)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc00009ded0, 0x1233f80, 0x4, 0x4, 0xc0b9b0e292792428)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc00011a000, 0x0)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/testing.go:1346 +0x273
main.main()
        _testmain.go:51 +0x138
FAIL    github.com/ebitengine/purego/objc       0.130s
FAIL
```

```
$ go1.16.15 test ./...
?       github.com/ebitengine/purego    [no test files]
?       github.com/ebitengine/purego/internal/fakecgo   [no test files]
?       github.com/ebitengine/purego/internal/strings   [no test files]
--- FAIL: ExampleAllocateClassPair (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x110edf4]

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc00010fd58, 0x0, 0x0, 0x16e10, 0x20300000000000, 0x112c280, 0x1229dc0, 0x1529200)
        /Users/hajimehoshi/sdk/go1.16.15/src/testing/example.go:91 +0x69b
testing.runExample.func2(0xc0b9b06081eed3c8, 0x948ba, 0x1231ec0, 0xc000010050, 0xc000010018, 0xc000074240, 0xc00010fd58, 0xc00010fcb6, 0xc00010fd88)
        /Users/hajimehoshi/sdk/go1.16.15/src/testing/run_example.go:59 +0x11c
panic(0x112c280, 0x1229dc0)
        /Users/hajimehoshi/sdk/go1.16.15/src/runtime/panic.go:965 +0x1b9
github.com/ebitengine/purego.callbackWrap(0x2)
        /Users/hajimehoshi/purego/syscall_darwin.go:102 +0x54
github.com/ebitengine/purego.syscall_syscall9X(0x7ff80afe3400, 0x600000008040, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/hajimehoshi/purego/syscall_darwin.go:20 +0x128
github.com/ebitengine/purego.SyscallN(0x7ff80afe3400, 0xc00001a1f0, 0x2, 0x2, 0x0, 0xc00001a1f0, 0x2)
        /Users/hajimehoshi/purego/syscall.go:37 +0x11e
github.com/ebitengine/purego/objc.ID.Send(0x600000008040, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin.go:52 +0xb7
github.com/ebitengine/purego/objc_test.ExampleAllocateClassPair()
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin_test.go:22 +0x1b3
testing.runExample(0x1152bba, 0x18, 0x11588f8, 0x115025e, 0xd, 0x0, 0x0)
        /Users/hajimehoshi/sdk/go1.16.15/src/testing/run_example.go:63 +0x222
testing.runExamples(0xc00010fed0, 0x122e780, 0x4, 0x4, 0xc0b9b0f681ed4940)
        /Users/hajimehoshi/sdk/go1.16.15/src/testing/example.go:44 +0x17a
testing.(*M).Run(0xc000126000, 0x0)
        /Users/hajimehoshi/sdk/go1.16.15/src/testing/testing.go:1428 +0x273
main.main()
        _testmain.go:51 +0x138
FAIL    github.com/ebitengine/purego/objc       0.123s
FAIL
```

**Comment by TotallyGamerJet** [comment]
It looks like it is

**Comment by TotallyGamerJet** [comment]
So it fails on amd64 (1.15 & 1.16) and on arm64 (1.16 & 1.17). This is because these version use stack based calling convention.

**Comment by hajimehoshi** [comment]
Thanks! I'll re-revert Oto later (maybe tomorrow)
