### ISSUE TITLE
SIGSEGV with gotip when using -race

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#71]
Do: `CGO_ENABLED=0 gotip run -race ./example/main.go` and receive `signal: segmentation fault`.

[Go 1.20](https://go-review.googlesource.com/c/go/+/451055l) rewrote the race detector to not require a C compiler on macOS. That's exciting! However, it break fakecgo. :(

The issue occurs in calling `x_cgo_init` from `x_cgo_init_trampoline` because it adds a bunch of calls to race functions. These race functions are not allowed in this Go code pretending to be C. Adding `//go:norace` does work in removing the race calls in the function itself but since we are calling this function from assembly it goes through the `ABI0` stub which still has the race code despite the comment. Ugh

```
TEXT github.com/ebitengine/purego/internal/fakecgo.x_cgo_init(SB) 
0x10f2400		4881ec98000000		SUBQ $0x98, SP										
0x10f2407		4889ac2490000000	MOVQ BP, 0x90(SP)									
0x10f240f		488dac2490000000	LEAQ 0x90(SP), BP									
0x10f2417		48898424a0000000	MOVQ AX, 0xa0(SP)									
0x10f241f		48899c24a8000000	MOVQ BX, 0xa8(SP)									
0x10f2427		488b842498000000	MOVQ 0x98(SP), AX									
0x10f242f		4889442420		MOVQ AX, 0x20(SP)									
0x10f2434		e8278ffcff		CALL runtime.racefuncenter(SB)								
0x10f2439		48c744241000000000	MOVQ $0x0, 0x10(SP)									
0x10f2442		440f117c2428		MOVUPS X15, 0x28(SP)									
0x10f2448		440f117c2438		MOVUPS X15, 0x38(SP)									
0x10f244e		440f117c2448		MOVUPS X15, 0x48(SP)									
0x10f2454		440f117c2458		MOVUPS X15, 0x58(SP)									
0x10f245a		488b8c24a8000000	MOVQ 0xa8(SP), CX									
0x10f2462		48894c2418		MOVQ CX, 0x18(SP)									
0x10f2467		488d0552a51100		LEAQ github.com/ebitengine/purego/internal/fakecgo.setg_func(SB), AX			
0x10f246e		e84d7afcff		CALL runtime.racewrite(SB)								
0x10f2473		488b4c2418		MOVQ 0x18(SP), CX									
0x10f2478		48890d41a51100		MOVQ CX, github.com/ebitengine/purego/internal/fakecgo.setg_func(SB)			
0x10f247f		488d442428		LEAQ 0x28(SP), AX									
0x10f2484		4889842480000000	MOVQ AX, 0x80(SP)									
0x10f248c		e86f090000		CALL github.com/ebitengine/purego/internal/fakecgo.pthread_attr_init(SB)		
0x10f2491		488d4c2428		LEAQ 0x28(SP), CX									
0x10f2496		48894c2478		MOVQ CX, 0x78(SP)									
0x10f249b		488d5c2410		LEAQ 0x10(SP), BX									
0x10f24a0		48895c2470		MOVQ BX, 0x70(SP)									
0x10f24a5		488b442478		MOVQ 0x78(SP), AX									
0x10f24aa		e8910e0000		CALL github.com/ebitengine/purego/internal/fakecgo.pthread_attr_getstacksize(SB)	
0x10f24af		488b8424a0000000	MOVQ 0xa0(SP), AX									
0x10f24b7		4889842488000000	MOVQ AX, 0x88(SP)									
0x10f24bf		8400			TESTB AL, 0(AX)										
0x10f24c1		488d4c2410		LEAQ 0x10(SP), CX									
0x10f24c6		482b4c2410		SUBQ 0x10(SP), CX									
0x10f24cb		48894c2418		MOVQ CX, 0x18(SP)									
0x10f24d0		e8eb79fcff		CALL runtime.racewrite(SB)								
0x10f24d5		488b4c2418		MOVQ 0x18(SP), CX									
0x10f24da		4881c100100000		ADDQ $0x1000, CX									
0x10f24e1		488b942488000000	MOVQ 0x88(SP), DX									
0x10f24e9		48890a			MOVQ CX, 0(DX)										
0x10f24ec		488d442428		LEAQ 0x28(SP), AX									
0x10f24f1		4889442468		MOVQ AX, 0x68(SP)									
0x10f24f6		e8a50f0000		CALL github.com/ebitengine/purego/internal/fakecgo.pthread_attr_destroy(SB)		
0x10f24fb		0f1f440000		NOPL 0(AX)(AX*1)									
0x10f2500		e89b8efcff		CALL runtime.racefuncexit(SB)								
0x10f2505		488bac2490000000	MOVQ 0x90(SP), BP									
0x10f250d		4881c498000000		ADDQ $0x98, SP										
0x10f2514		c3			RET		
```

If this was in the runtime we could just call the function as ABIInternal and save all the hassle. The only solution I can currently think of is to compile the `runtime/cgo` version and then convert that to go assembly similar to [c2goasm](https://github.com/minio/c2goasm). 

@hajimehoshi do you think we should petition that `CALL ·x_cgo_init<ABIInternal>(SB)` be allowed outside the runtime? Even if it means we have to be careful about calling convention. Or perhaps, it's more likely that `//go:norace` should also affect the ABI0 stubs? It might be a bug none the less so that might be more likely to be approved.

**Comment by TotallyGamerJet** [comment]
Another solution that doesn't depend on the Go team is to go back to using `runtime.libcCall` instead of `runtime.cgocall`. Which would remove the need for fakecgo (on darwin) I believe but I will test that to make sure.

**Comment by hajimehoshi** [comment]
So the problem is that the race detector is in pure Go and then the current fakecgo doesn't work as this would have to call the race functions, right?

> do you think we should petition that CALL ·x_cgo_init<ABIInternal>(SB) be allowed outside the runtime?

I'm afraid I don't understand your suggestion.

> However, we'll need to be careful with goroutines by using runtime.LockOSThread like we had to in https://github.com/ebitengine/purego/pull/15 for the test.

Is LockOSThread required for all goroutines, or only for an init function?

**Comment by TotallyGamerJet** [comment]
> So the problem is that the race detector is in pure Go and then the current fakecgo doesn't work as this would have to call the race functions, right?
> 

Yes the race detector in Go 1.20 (gotip) is in pure go and so it will effect our code when CGO_ENABLED=0. fakecgo which is effected by this change is called before the runtime is even fully setup so running race detector functions in it is bad.

> > do you think we should petition that CALL ·x_cgo_init<ABIInternal>(SB) be allowed outside the runtime?
> 
> 
> 
> I'm afraid I don't understand your suggestion.
> 


The `<ABIInternal>` part is only valid in the runtime. If we had it available outside it would let us avoid calling the `ABI0` wrapper that Go generates when calling a function from assembly. This wrapper still has the race detector functions even when the function has `//go:norace`.

> Is LockOSThread required for all goroutines, or only for an init function?

I'm not sure. I'll test.

**Comment by TotallyGamerJet** [comment]
The more that I think about it the more I think `//go:norace` should effect ABI0 wrappers.

**Comment by hajimehoshi** [comment]
> The <ABIInternal> part is only valid in the runtime. If we had it available outside it would let us avoid calling the ABI0 wrapper that Go generates when calling a function from assembly. This wrapper still has the race detector functions even when the function has //go:norace.

I see. I don't think it is feasible to make it available outside of the runtime (by asking the Go team?).

> Another solution that doesn't depend on the Go team is to go back to using runtime.libcCall instead of runtime.cgocall. 

I was wondering how libcCall instead of cgocall would resolve the issue, but this seems nice if it works.

For LockOSThread, it's OK if it is needed only for init functions. We need to add a documentation about this.

**Comment by hajimehoshi** [comment]
> > Another solution that doesn't depend on the Go team is to go back to using runtime.libcCall instead of runtime.cgocall.
>
> I was wondering how libcCall instead of cgocall would resolve the issue, but this seems nice if it works.

Perhaps, libcCall doesn't require runtime/cgo while cgocall requires it, is that correct?

**Comment by TotallyGamerJet** [comment]
> I see. I don't think it is feasible to make it available outside of the runtime (by asking the Go team?). As the feature freezing started, we cannot make it in Go 1.20 anyway.

Well that's unfortunate. I still think making an issue for `//go:norace` might still be an option since if it's a bug it could get fixed in a bug release.

> For LockOSThread, it's OK if it is needed only for init functions. We need to add a documentation about this.

Preliminary tests seem like it needs to be each Go routine? It's very finicky and the Otto example would not play any sound although it would run without crashing.

**Comment by TotallyGamerJet** [comment]
> Perhaps, libcCall doesn't require runtime/cgo while cgocall requires it, is that correct?

This is right. cgocall checks to make sure runtime/cgo is there. Which is why we needed to create fakecgo to fake that package. libcCall does not check that cgo is available. However it doesn't seem to play nice with goroutines moving around

**Comment by hajimehoshi** [comment]
https://github.com/ebitengine/purego/blob/05c1074240f7a8180257bbb8a1d487937744da5b/func.go#L188

Don't we need `//go:nosplit` here?

**Comment by TotallyGamerJet** [comment]
It should be okay to split because all the arguments are on the heap because they are stored in recflect.Value.

**Comment by TotallyGamerJet** [comment]
My branch [gotip](https://github.com/TotallyGamerJet/purego/tree/gotip) can be used to test. It currently has the changes for `runtime.libcCall` instead of `runtime.cgocall`.

**Comment by hajimehoshi** [comment]
Thanks, I've tested this. Apparently `m.incgo` is unexpectedly true (at libcCall in RegisterFunc?)

**Comment by hajimehoshi** [comment]
I have tested your gotip branch (e33e637d5721663eafc0f7bcd7bd326e0feb53f8):

```
$ go version
go version go1.19.2 darwin/amd64
```

```
$ go test ./objc
fatal error: schedule: in cgo

runtime stack:
runtime.throw({0x1135714?, 0x1222c40?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bfeff500 sp=0x7ff7bfeff4d0 pc=0x1035c7d
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3192 +0x23f fp=0x7ff7bfeff538 sp=0x7ff7bfeff500 pc=0x103ec7f
runtime.park_m(0xc0000061a0?)
	/usr/local/go/src/runtime/proc.go:3355 +0x14d fp=0x7ff7bfeff568 sp=0x7ff7bfeff538 pc=0x103f02d
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:448 +0x43 fp=0x7ff7bfeff578 sp=0x7ff7bfeff568 pc=0x1064603

goroutine 1 [chan receive]:
runtime.gopark(0x1115860?, 0xc000207a50?, 0xe0?, 0x87?, 0xc000207a88?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000207a28 sp=0xc000207a08 pc=0x1038856
runtime.chanrecv(0xc00008e780, 0xc000207b60, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc000207ab8 sp=0xc000207a28 pc=0x1006e9b
runtime.chanrecv1(0xc0000a2240?, 0x0?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc000207ae0 sp=0xc000207ab8 pc=0x10069d8
testing.runExample.func2()
	/usr/local/go/src/testing/run_example.go:56 +0xce fp=0xc000207b80 sp=0xc000207ae0 pc=0x10bb60e
testing.runExample({{0x11378a7, 0x18}, 0x113e8b0, {0x1134b85, 0xd}, 0x0})
	/usr/local/go/src/testing/run_example.go:65 +0x2a4 fp=0xc000207c68 sp=0xc000207b80 pc=0x10bb4c4
testing.runExamples(0xc000207e58, {0x121e920?, 0x4, 0x0?})
	/usr/local/go/src/testing/example.go:44 +0x186 fp=0xc000207d08 sp=0xc000207c68 pc=0x10b7246
testing.(*M).Run(0xc0000c20a0)
	/usr/local/go/src/testing/testing.go:1728 +0x689 fp=0xc000207f00 sp=0xc000207d08 pc=0x10c07a9
main.main()
	_testmain.go:55 +0x1aa fp=0xc000207f80 sp=0xc000207f00 pc=0x1102baa
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000207fe0 sp=0xc000207f80 pc=0x1038492
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000207fe8 sp=0xc000207fe0 pc=0x1066861

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004cfb0 sp=0xc00004cf90 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00004cfe0 sp=0xc00004cfb0 pc=0x10386ed
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x1066861
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004d790 sp=0xc00004d770 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00004d7c8 sp=0xc00004d790 pc=0x1023fce
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x1018c86
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x1066861
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000028070?, 0x1163110?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004df70 sp=0xc00004df50 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1222ac0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x1022073
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x1022645
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x1018c26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x1066861
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x12231e0?, 0xc0000824e0?, 0x0?, 0x0?, 0xc00004c770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004c628 sp=0xc00004c608 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00004c7e0 sp=0xc00004c628 pc=0x1017d8f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x1066861
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 19 [runnable]:
runtime.mallocgc(0x10?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/malloc.go:842 +0x8d1 fp=0xc000048618 sp=0xc000048610 pc=0x100d931
runtime.growslice(0xc000182000?, {0x0?, 0x8000?, 0xd?}, 0x104b912?)
	/usr/local/go/src/runtime/slice.go:284 +0x4ac fp=0xc000048680 sp=0xc000048618 pc=0x104becc
strings.(*Builder).Write(0xc000180000, {0xc000182000, 0xd, 0x1334a68?})
	/usr/local/go/src/strings/builder.go:90 +0x85 fp=0xc0000486d0 sp=0xc000048680 pc=0x10aa925
io.copyBuffer({0x1163dc0, 0xc000180000}, {0x1163d00, 0xc0000a00d0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:429 +0x204 fp=0xc000048750 sp=0xc0000486d0 pc=0x10800e4
io.Copy(...)
	/usr/local/go/src/io/io.go:386
testing.runExample.func1()
	/usr/local/go/src/testing/run_example.go:37 +0x76 fp=0xc0000487e0 sp=0xc000048750 pc=0x10bb6f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x1066861
created by testing.runExample
	/usr/local/go/src/testing/run_example.go:35 +0x1c5
FAIL	github.com/ebitengine/purego/objc	0.122s
FAIL

```

**Comment by cuonglm** [comment]
I think the problem is that the compiler know `x_cgo_init` is the native `ABI0`, so it optimizes the call to use `ABI0` directly.

One way to workaround:

```
diff --git a/internal/fakecgo/go_darwin_amd64.go b/internal/fakecgo/go_darwin_amd64.go
index 7301870..96e3395 100644
--- a/internal/fakecgo/go_darwin_amd64.go
+++ b/internal/fakecgo/go_darwin_amd64.go
@@ -58,6 +58,7 @@ func threadentry(v unsafe.Pointer) unsafe.Pointer {
 var setg_func uintptr
 
 //go:nosplit
+//go:norace
 func x_cgo_init(g *G, setg uintptr) {
        var size size_t
        var attr pthread_attr_t
@@ -68,3 +69,5 @@ func x_cgo_init(g *G, setg uintptr) {
        g.stacklo = uintptr(unsafe.Pointer(&size)) - uintptr(size) + 4096
        pthread_attr_destroy(&attr)
 }
+
+var x_cgo_init_call = x_cgo_init
diff --git a/internal/fakecgo/trampolines_amd64.s b/internal/fakecgo/trampolines_amd64.s
index 2665f62..72f7e54 100644
--- a/internal/fakecgo/trampolines_amd64.s
+++ b/internal/fakecgo/trampolines_amd64.s
@@ -31,7 +31,7 @@ return value will be in AX
 TEXT x_cgo_init_trampoline(SB), NOSPLIT, $16
        MOVQ DI, 0(SP)
        MOVQ SI, 8(SP)
-       CALL ·x_cgo_init(SB)
+       CALL ·x_cgo_init_call(SB)
        RET
 
 TEXT x_cgo_thread_start_trampoline(SB), NOSPLIT, $8
```

**Comment by TotallyGamerJet** [comment]
I tried your change:

```
jarrettkuklis@jarretts-mbp purego % CGO_ENABLED=0 GOARCH=amd64 gotip run -race ./example/main.go
signal: bus error
```
It does not make it into the function body. I tested by using `CALL purego_abort(SB)` before and after and directly in the function body.

```
diff --git a/internal/fakecgo/go_darwin_amd64.go b/internal/fakecgo/go_darwin_amd64.go
index 7301870..d873c0a 100644
--- a/internal/fakecgo/go_darwin_amd64.go
+++ b/internal/fakecgo/go_darwin_amd64.go
@@ -57,7 +57,10 @@ func threadentry(v unsafe.Pointer) unsafe.Pointer {
 // here we will store a pointer to the provided setg func
 var setg_func uintptr
 
+var x_cgo_init_call = x_cgo_init
+
 //go:nosplit
+//go:norace
 func x_cgo_init(g *G, setg uintptr) {
 	var size size_t
 	var attr pthread_attr_t
diff --git a/internal/fakecgo/go_darwin_arm64.go b/internal/fakecgo/go_darwin_arm64.go
index 462f18e..b6ad4fa 100644
--- a/internal/fakecgo/go_darwin_arm64.go
+++ b/internal/fakecgo/go_darwin_arm64.go
@@ -61,12 +61,15 @@ func threadentry(v unsafe.Pointer) unsafe.Pointer {
 // here we will store a pointer to the provided setg func
 var setg_func uintptr
 
+var x_cgo_init_call = x_cgo_init
+
 // x_cgo_init(G *g, void (*setg)(void*)) (runtime/cgo/gcc_linux_amd64.c)
 // This get's called during startup, adjusts stacklo, and provides a pointer to setg_gcc for us
 // Additionally, if we set _cgo_init to non-null, go won't do it's own TLS setup
 // This function can't be go:systemstack since go is not in a state where the systemcheck would work.
 //
 //go:nosplit
+//go:norace
 func x_cgo_init(g *G, setg uintptr) {
 	var size size_t
 	var attr pthread_attr_t
diff --git a/internal/fakecgo/go_util.go b/internal/fakecgo/go_util.go
index e371ac1..0407a1c 100644
--- a/internal/fakecgo/go_util.go
+++ b/internal/fakecgo/go_util.go
@@ -8,6 +8,7 @@ package fakecgo
 import "unsafe"
 
 // _cgo_thread_start is split into three parts in cgo since only one part is system dependent (keep it here for easier handling)
+var x_cgo_thread_start_call = x_cgo_thread_start
 
 // _cgo_thread_start(ThreadStart *arg) (runtime/cgo/gcc_util.c)
 // This get's called instead of the go code for creating new threads
@@ -16,6 +17,7 @@ import "unsafe"
 // This function should be go:systemstack instead of go:nosplit (but that requires runtime)
 //
 //go:nosplit
+//go:norace
 func x_cgo_thread_start(arg *ThreadStart) {
 	var ts *ThreadStart
 	// Make our own copy that can persist after we return.
diff --git a/internal/fakecgo/trampolines_amd64.s b/internal/fakecgo/trampolines_amd64.s
index 2665f62..b67b6bb 100644
--- a/internal/fakecgo/trampolines_amd64.s
+++ b/internal/fakecgo/trampolines_amd64.s
@@ -31,12 +31,12 @@ return value will be in AX
 TEXT x_cgo_init_trampoline(SB), NOSPLIT, $16
 	MOVQ DI, 0(SP)
 	MOVQ SI, 8(SP)
-	CALL ·x_cgo_init(SB)
+	CALL ·x_cgo_init_call(SB)
 	RET
 
 TEXT x_cgo_thread_start_trampoline(SB), NOSPLIT, $8
 	MOVQ DI, 0(SP)
-	CALL ·x_cgo_thread_start(SB)
+	CALL ·x_cgo_thread_start_call(SB)
 	RET
 
 TEXT x_cgo_setenv_trampoline(SB), NOSPLIT, $8
diff --git a/internal/fakecgo/trampolines_arm64.s b/internal/fakecgo/trampolines_arm64.s
index c4ff876..665c4dd 100644
--- a/internal/fakecgo/trampolines_arm64.s
+++ b/internal/fakecgo/trampolines_arm64.s
@@ -11,12 +11,12 @@
 TEXT x_cgo_init_trampoline(SB), NOSPLIT, $0-0
 	MOVD R0, 8(RSP)
 	MOVD R1, 16(RSP)
-	CALL ·x_cgo_init(SB)
+	CALL ·x_cgo_init_call(SB)
 	RET
 
 TEXT x_cgo_thread_start_trampoline(SB), NOSPLIT, $0-0
 	MOVD R0, 8(RSP)
-	CALL ·x_cgo_thread_start(SB)
+	CALL ·x_cgo_thread_start_call(SB)
 	RET
 
 TEXT x_cgo_setenv_trampoline(SB), NOSPLIT, $0-0
```

**Comment by cuonglm** [comment]
@TotallyGamerJet Forgot that we need to setup thing for closure call now, something like this:

```
diff --git a/internal/fakecgo/go_darwin_arm64.go b/internal/fakecgo/go_darwin_arm64.go
index 462f18e..b6ad4fa 100644
--- a/internal/fakecgo/go_darwin_arm64.go
+++ b/internal/fakecgo/go_darwin_arm64.go
@@ -61,12 +61,15 @@ func threadentry(v unsafe.Pointer) unsafe.Pointer {
 // here we will store a pointer to the provided setg func
 var setg_func uintptr

+var x_cgo_init_call = x_cgo_init
+
 // x_cgo_init(G *g, void (*setg)(void*)) (runtime/cgo/gcc_linux_amd64.c)
 // This get's called during startup, adjusts stacklo, and provides a pointer to setg_gcc for us
 // Additionally, if we set _cgo_init to non-null, go won't do it's own TLS setup
 // This function can't be go:systemstack since go is not in a state where the systemcheck would work.
 //
 //go:nosplit
+//go:norace
 func x_cgo_init(g *G, setg uintptr) {
        var size size_t
        var attr pthread_attr_t
diff --git a/internal/fakecgo/trampolines_arm64.s b/internal/fakecgo/trampolines_arm64.s
index c4ff876..a748763 100644
--- a/internal/fakecgo/trampolines_arm64.s
+++ b/internal/fakecgo/trampolines_arm64.s
@@ -8,10 +8,12 @@

 // these trampolines map the gcc ABI to Go ABI and then calls into the Go equivalent functions.

-TEXT x_cgo_init_trampoline(SB), NOSPLIT, $0-0
+TEXT x_cgo_init_trampoline(SB), NOSPLIT,$0-0
+       MOVD ·x_cgo_init_call(SB), R26
+       MOVD (R26), R2
        MOVD R0, 8(RSP)
        MOVD R1, 16(RSP)
-       CALL ·x_cgo_init(SB)
+       CALL (R2)
        RET

 TEXT x_cgo_thread_start_trampoline(SB), NOSPLIT, $0-0
```

Now we get a better runtime crash:

```
$ CGO_ENABLED=0 go run -race ./example/main.go
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1047bbf3c]

runtime stack:
runtime.throw({0x104880f0e?, 0xc0000029c0?})
	/Users/cuonglm/sources/go/src/runtime/panic.go:1047 +0x40 fp=0x16b6472c0 sp=0x16b647290 pc=0x104826a50
runtime.sigpanic()
	/Users/cuonglm/sources/go/src/runtime/signal_unix.go:821 +0x240 fp=0x16b647300 sp=0x16b6472c0 pc=0x10483c4b0

goroutine 1 [running]:
runtime.systemstack_switch()
	/Users/cuonglm/sources/go/src/runtime/asm_arm64.s:200 +0x8 fp=0xc000046770 sp=0xc000046760 pc=0x104851708
runtime.main()
	/Users/cuonglm/sources/go/src/runtime/proc.go:170 +0x6c fp=0xc0000467d0 sp=0xc000046770 pc=0x104828e7c
runtime.goexit()
	/Users/cuonglm/sources/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0xc0000467d0 sp=0xc0000467d0 pc=0x104853cc4
exit status 2
```

**Comment by TotallyGamerJet** [comment]
@cuonglm Thank you very much! I used godbolt to see how closure calls are done on amd64 and now purego is working successfully on amd64 and arm64!

**Comment by hajimehoshi** [comment]
OK I temporarily allowed force-push, force-pushed, and then disallowed it again.
